### ISSUE TITLE
[Todo] Implement art assets

### ISSUE THREAD

**Issue by 53854** [53854/VR-Driving#2]
### **Add and implement current art assets** 
Import new Models, Art, Auto, etc. to Unity Project

- [ ] Creat relevant folders in Assets if not existing yet
- Create adequate sub-folders related to differnt artstyles if needed
- [ ] Import new Models
- attach relevant textures/materials 
- create **usable prefabs**

- [ ] Utilize `<AssetPack>` Prefab to implement
- Create Corrosponding Asset-Packs for easy implementation
-> Duplicate prefab in folder 
-> Drag duplicat into scene 
-> Assign refferences from Prefab folder 
->Save as new Prefab

- [ ] Import relevant audio
